name: Scrape Products

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Validate environment variables
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_KEY" ]; then
            echo "Error: SUPABASE_KEY is not set"
            exit 1
          fi
          echo "Environment variables validated successfully"

      - name: Run scraper
        run: |
          echo "Starting product scraper..."
          npx tsx src/scripts/scrape-products.ts
        env:
          NODE_ENV: production 