name: Scrape Products

on:
  schedule:
    - cron: '0 0 * * 1,3'  # Run at midnight (00:00) on Monday (1) and Wednesday (3)
  workflow_dispatch:  # Allow manual trigger

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate subcategory chunks
        id: set-matrix
        run: |
          # Generate 40 chunks from the subcategories
          node -e '
          const chunks = Array.from({ length: 40 }, (_, i) => i);
          console.log(`::set-output name=matrix::${JSON.stringify({chunk: chunks})}`);
          '

  scrape:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
      fail-fast: false
    
    env:
      SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      CHUNK_INDEX: ${{ matrix.chunk }}
      TOTAL_CHUNKS: 40

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Validate environment variables
        run: |
          if [ -z "$SUPABASE_URL" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_KEY" ]; then
            echo "Error: SUPABASE_KEY is not set"
            exit 1
          fi
          echo "Environment variables validated successfully"

      - name: Run scraper
        run: |
          echo "Starting product scraper for chunk $CHUNK_INDEX of $TOTAL_CHUNKS..."
          npx tsx src/scripts/scrape-products.ts
        env:
          NODE_ENV: production 